//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region Employee
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Employee :
        global::LightSwitchApplication.Employee.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnUserNameChanged()
        {
            this.___OnPropertyChanged("UserName");
        }
        
        partial void OnLastNameChanged()
        {
            this.___OnPropertyChanged("LastName");
        }
        
        partial void OnFirstNameChanged()
        {
            this.___OnPropertyChanged("FirstName");
        }
        
        partial void OnEmailChanged()
        {
            this.___OnPropertyChanged("Email");
        }
        
        partial void OnCurrentChanged()
        {
            this.___OnPropertyChanged("Current");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.FurtherActions
        {
            get
            {
                return this.FurtherActions;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.FurtherAction> __FurtherActions
        {
            get
            {
                if (this.___FurtherActions == null)
                {
                    this.___FurtherActions = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.FurtherAction>(
                        this,
                        "FurtherActions",
                        () => this._FurtherActions,
                        e => global::System.Object.Equals(e.IssueAction_Employee, this.Id));
                }
                return this.___FurtherActions;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.FurtherAction> ___FurtherActions;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.IssueAssignments
        {
            get
            {
                return this.IssueAssignments;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Issue> __IssueAssignments
        {
            get
            {
                if (this.___IssueAssignments == null)
                {
                    this.___IssueAssignments = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Issue>(
                        this,
                        "IssueAssignments",
                        () => this._IssueAssignments,
                        e => global::System.Object.Equals(e.Issue_Employee, this.Id));
                }
                return this.___IssueAssignments;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Issue> ___IssueAssignments;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.OwnedIssues
        {
            get
            {
                return this.OwnedIssues;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Issue> __OwnedIssues
        {
            get
            {
                if (this.___OwnedIssues == null)
                {
                    this.___OwnedIssues = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Issue>(
                        this,
                        "OwnedIssues",
                        () => this._OwnedIssues,
                        e => global::System.Object.Equals(e.Issue_Employee1, this.Id));
                }
                return this.___OwnedIssues;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Issue> ___OwnedIssues;
        
    }
    #endregion
    
    #region FurtherAction
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class FurtherAction :
        global::LightSwitchApplication.FurtherAction.DetailsClass.IImplementation
    {
        partial void OnIssueAction_IssueChanged()
        {
            this.___OnPropertyChanged("IssueAction_Issue");
            this.___OnPropertyChanged("Issue");
        }
        
        partial void OnIssueAction_EmployeeChanged()
        {
            this.___OnPropertyChanged("IssueAction_Employee");
            this.___OnPropertyChanged("AssignedTo");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnActionTitleChanged()
        {
            this.___OnPropertyChanged("ActionTitle");
        }
        
        partial void OnActionOutcomeChanged()
        {
            this.___OnPropertyChanged("ActionOutcome");
        }
        
        partial void OnDateAssignedChanged()
        {
            this.___OnPropertyChanged("DateAssigned");
        }
        
        partial void OnTargetCompletionDateChanged()
        {
            this.___OnPropertyChanged("TargetCompletionDate");
        }
        
        partial void OnPercentCompletedChanged()
        {
            this.___OnPropertyChanged("PercentCompleted");
        }
        
        partial void OnPriorityChanged()
        {
            this.___OnPropertyChanged("Priority");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnDateCompletedChanged()
        {
            this.___OnPropertyChanged("DateCompleted");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.FurtherAction.DetailsClass.IImplementation.Issue
        {
            get
            {
                return this.Issue;
            }
            set
            {
                this.Issue = (global::LightSwitchApplication.Implementation.Issue)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Issue> __Issue
        {
            get
            {
                if (this.___Issue == null)
                {
                    this.___Issue = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Issue>(
                        this,
                        "Issue",
                        new string[] { "IssueAction_Issue" },
                        e => global::System.Object.Equals(e.Id, this.IssueAction_Issue),
                        () => this._Issue,
                        e => this._Issue = e);
                }
                return this.___Issue;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Issue> ___Issue;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.FurtherAction.DetailsClass.IImplementation.AssignedTo
        {
            get
            {
                return this.AssignedTo;
            }
            set
            {
                this.AssignedTo = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __AssignedTo
        {
            get
            {
                if (this.___AssignedTo == null)
                {
                    this.___AssignedTo = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "AssignedTo",
                        new string[] { "IssueAction_Employee" },
                        e => global::System.Object.Equals(e.Id, this.IssueAction_Employee),
                        () => this._AssignedTo,
                        e => this._AssignedTo = e);
                }
                return this.___AssignedTo;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___AssignedTo;
        
    }
    #endregion
    
    #region IssueComment
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class IssueComment :
        global::LightSwitchApplication.IssueComment.DetailsClass.IImplementation
    {
        partial void OnIssueComment_IssueChanged()
        {
            this.___OnPropertyChanged("IssueComment_Issue");
            this.___OnPropertyChanged("Issue");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnCommentChanged()
        {
            this.___OnPropertyChanged("Comment");
        }
        
        partial void OnCommentDateChanged()
        {
            this.___OnPropertyChanged("CommentDate");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.IssueComment.DetailsClass.IImplementation.Issue
        {
            get
            {
                return this.Issue;
            }
            set
            {
                this.Issue = (global::LightSwitchApplication.Implementation.Issue)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Issue> __Issue
        {
            get
            {
                if (this.___Issue == null)
                {
                    this.___Issue = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Issue>(
                        this,
                        "Issue",
                        new string[] { "IssueComment_Issue" },
                        e => global::System.Object.Equals(e.Id, this.IssueComment_Issue),
                        () => this._Issue,
                        e => this._Issue = e);
                }
                return this.___Issue;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Issue> ___Issue;
        
    }
    #endregion
    
    #region Issue
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Issue :
        global::LightSwitchApplication.Issue.DetailsClass.IImplementation
    {
        partial void OnIssue_Employee1Changed()
        {
            this.___OnPropertyChanged("Issue_Employee1");
            this.___OnPropertyChanged("IssueOwner");
        }
        
        partial void OnIssueType_IssueChanged()
        {
            this.___OnPropertyChanged("IssueType_Issue");
            this.___OnPropertyChanged("IssueType");
        }
        
        partial void OnIssue_EmployeeChanged()
        {
            this.___OnPropertyChanged("Issue_Employee");
            this.___OnPropertyChanged("AssignedTo");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnIssueTitleChanged()
        {
            this.___OnPropertyChanged("IssueTitle");
        }
        
        partial void OnDateRaisedChanged()
        {
            this.___OnPropertyChanged("DateRaised");
        }
        
        partial void OnIssueDescriptionChanged()
        {
            this.___OnPropertyChanged("IssueDescription");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnPriorityChanged()
        {
            this.___OnPropertyChanged("Priority");
        }
        
        partial void OnIssueImpactAssessmentChanged()
        {
            this.___OnPropertyChanged("IssueImpactAssessment");
        }
        
        partial void OnTargetResolutionDateChanged()
        {
            this.___OnPropertyChanged("TargetResolutionDate");
        }
        
        partial void OnCorrectiveActionChanged()
        {
            this.___OnPropertyChanged("CorrectiveAction");
        }
        
        partial void OnCorrectiveActionCompletionTargetDateChanged()
        {
            this.___OnPropertyChanged("CorrectiveActionCompletionTargetDate");
        }
        
        partial void OnDateCorrectiveActionCompletedChanged()
        {
            this.___OnPropertyChanged("DateCorrectiveActionCompleted");
        }
        
        partial void OnPreventativeActionChanged()
        {
            this.___OnPropertyChanged("PreventativeAction");
        }
        
        partial void OnPreventativeActionCompletionTargetDateChanged()
        {
            this.___OnPropertyChanged("PreventativeActionCompletionTargetDate");
        }
        
        partial void OnDatePreventativeActionCompletedChanged()
        {
            this.___OnPropertyChanged("DatePreventativeActionCompleted");
        }
        
        partial void OnDateIssueClosedChanged()
        {
            this.___OnPropertyChanged("DateIssueClosed");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Issue.DetailsClass.IImplementation.IssueOwner
        {
            get
            {
                return this.IssueOwner;
            }
            set
            {
                this.IssueOwner = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __IssueOwner
        {
            get
            {
                if (this.___IssueOwner == null)
                {
                    this.___IssueOwner = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "IssueOwner",
                        new string[] { "Issue_Employee1" },
                        e => global::System.Object.Equals(e.Id, this.Issue_Employee1),
                        () => this._IssueOwner,
                        e => this._IssueOwner = e);
                }
                return this.___IssueOwner;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___IssueOwner;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Issue.DetailsClass.IImplementation.IssueType
        {
            get
            {
                return this.IssueType;
            }
            set
            {
                this.IssueType = (global::LightSwitchApplication.Implementation.IssueType)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.IssueType> __IssueType
        {
            get
            {
                if (this.___IssueType == null)
                {
                    this.___IssueType = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.IssueType>(
                        this,
                        "IssueType",
                        new string[] { "IssueType_Issue" },
                        e => global::System.Object.Equals(e.Id, this.IssueType_Issue),
                        () => this._IssueType,
                        e => this._IssueType = e);
                }
                return this.___IssueType;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.IssueType> ___IssueType;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Issue.DetailsClass.IImplementation.AssignedTo
        {
            get
            {
                return this.AssignedTo;
            }
            set
            {
                this.AssignedTo = (global::LightSwitchApplication.Implementation.Employee)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> __AssignedTo
        {
            get
            {
                if (this.___AssignedTo == null)
                {
                    this.___AssignedTo = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee>(
                        this,
                        "AssignedTo",
                        new string[] { "Issue_Employee" },
                        e => global::System.Object.Equals(e.Id, this.Issue_Employee),
                        () => this._AssignedTo,
                        e => this._AssignedTo = e);
                }
                return this.___AssignedTo;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Employee> ___AssignedTo;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Issue.DetailsClass.IImplementation.FurtherActions
        {
            get
            {
                return this.FurtherActions;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.FurtherAction> __FurtherActions
        {
            get
            {
                if (this.___FurtherActions == null)
                {
                    this.___FurtherActions = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.FurtherAction>(
                        this,
                        "FurtherActions",
                        () => this._FurtherActions,
                        e => global::System.Object.Equals(e.IssueAction_Issue, this.Id));
                }
                return this.___FurtherActions;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.FurtherAction> ___FurtherActions;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Issue.DetailsClass.IImplementation.IssueComments
        {
            get
            {
                return this.IssueComments;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IssueComment> __IssueComments
        {
            get
            {
                if (this.___IssueComments == null)
                {
                    this.___IssueComments = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IssueComment>(
                        this,
                        "IssueComments",
                        () => this._IssueComments,
                        e => global::System.Object.Equals(e.IssueComment_Issue, this.Id));
                }
                return this.___IssueComments;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.IssueComment> ___IssueComments;
        
    }
    #endregion
    
    #region IssueType
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class IssueType :
        global::LightSwitchApplication.IssueType.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnIssueTypeNameChanged()
        {
            this.___OnPropertyChanged("IssueTypeName");
        }
        
        partial void OnCreatedByChanged()
        {
            this.___OnPropertyChanged("CreatedBy");
        }
        
        partial void OnCreatedChanged()
        {
            this.___OnPropertyChanged("Created");
        }
        
        partial void OnModifiedByChanged()
        {
            this.___OnPropertyChanged("ModifiedBy");
        }
        
        partial void OnModifiedChanged()
        {
            this.___OnPropertyChanged("Modified");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.IssueType.DetailsClass.IImplementation.Issues
        {
            get
            {
                return this.Issues;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Issue> __Issues
        {
            get
            {
                if (this.___Issues == null)
                {
                    this.___Issues = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Issue>(
                        this,
                        "Issues",
                        () => this._Issues,
                        e => global::System.Object.Equals(e.IssueType_Issue, this.Id));
                }
                return this.___Issues;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Issue> ___Issues;
        
    }
    #endregion
    
    #region ApplicationData
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationData
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.FurtherAction))
            {
                return new global::LightSwitchApplication.Implementation.FurtherAction();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.IssueComment))
            {
                return new global::LightSwitchApplication.Implementation.IssueComment();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Issue))
            {
                return new global::LightSwitchApplication.Implementation.Issue();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.IssueType))
            {
                return new global::LightSwitchApplication.Implementation.IssueType();
            }
            return null;
        }
        
        protected override void InitializeDataServiceContext()
        {
            this.Format.LoadServiceModel = global::LightSwitchApplication.Implementation.ApplicationData.GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationData(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Employee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Employee);
            }
            if (typeof(global::LightSwitchApplication.FurtherAction) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.FurtherAction);
            }
            if (typeof(global::LightSwitchApplication.IssueComment) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.IssueComment);
            }
            if (typeof(global::LightSwitchApplication.Issue) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Issue);
            }
            if (typeof(global::LightSwitchApplication.IssueType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.IssueType);
            }
            return null;
        }
    }
}
