//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FurtherAction_Employee", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Employee), "FurtherAction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.FurtherAction), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "Issue_Employee", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LightSwitchApplication.Implementation.Employee), "Issue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Issue), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "Issue_Employee1", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Employee), "Issue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Issue), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "FurtherAction_Issue", "Issue", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Issue), "FurtherAction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.FurtherAction), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "IssueComment_Issue", "Issue", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.Issue), "IssueComment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.IssueComment), true)]
[assembly: EdmRelationshipAttribute("LightSwitchApplication", "IssueType_Issue", "IssueType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LightSwitchApplication.Implementation.IssueType), "Issue", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LightSwitchApplication.Implementation.Issue), true)]

#endregion

namespace LightSwitchApplication.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ApplicationData : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ApplicationData object using the connection string found in the 'ApplicationData' section of the application configuration file.
        /// </summary>
        public ApplicationData() : base("name=ApplicationData", "ApplicationData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationData object.
        /// </summary>
        public ApplicationData(string connectionString) : base(connectionString, "ApplicationData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationData object.
        /// </summary>
        public ApplicationData(EntityConnection connection) : base(connection, "ApplicationData")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employees
        {
            get
            {
                if ((_Employees == null))
                {
                    _Employees = base.CreateObjectSet<Employee>("Employees");
                }
                return _Employees;
            }
        }
        private ObjectSet<Employee> _Employees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FurtherAction> FurtherActions
        {
            get
            {
                if ((_FurtherActions == null))
                {
                    _FurtherActions = base.CreateObjectSet<FurtherAction>("FurtherActions");
                }
                return _FurtherActions;
            }
        }
        private ObjectSet<FurtherAction> _FurtherActions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<IssueComment> IssueComments
        {
            get
            {
                if ((_IssueComments == null))
                {
                    _IssueComments = base.CreateObjectSet<IssueComment>("IssueComments");
                }
                return _IssueComments;
            }
        }
        private ObjectSet<IssueComment> _IssueComments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Issue> Issues
        {
            get
            {
                if ((_Issues == null))
                {
                    _Issues = base.CreateObjectSet<Issue>("Issues");
                }
                return _Issues;
            }
        }
        private ObjectSet<Issue> _Issues;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<IssueType> IssueTypes
        {
            get
            {
                if ((_IssueTypes == null))
                {
                    _IssueTypes = base.CreateObjectSet<IssueType>("IssueTypes");
                }
                return _IssueTypes;
            }
        }
        private ObjectSet<IssueType> _IssueTypes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FurtherActions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFurtherActions(FurtherAction furtherAction)
        {
            base.AddObject("FurtherActions", furtherAction);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the IssueComments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIssueComments(IssueComment issueComment)
        {
            base.AddObject("IssueComments", issueComment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Issues EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIssues(Issue issue)
        {
            base.AddObject("Issues", issue);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the IssueTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIssueTypes(IssueType issueType)
        {
            base.AddObject("IssueTypes", issueType);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="current">Initial value of the Current property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        public static Employee CreateEmployee(global::System.Int32 id, global::System.String userName, global::System.String lastName, global::System.String firstName, global::System.String email, global::System.Boolean current, global::System.Byte[] rowVersion)
        {
            Employee employee = new Employee();
            employee.Id = id;
            employee.UserName = userName;
            employee.LastName = lastName;
            employee.FirstName = firstName;
            employee.Email = email;
            employee.Current = current;
            employee.RowVersion = rowVersion;
            return employee;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = value;
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = value;
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = value;
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = value;
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Current
        {
            get
            {
                return _Current;
            }
            set
            {
                OnCurrentChanging(value);
                ReportPropertyChanging("Current");
                _Current = value;
                ReportPropertyChanged("Current");
                OnCurrentChanged();
            }
        }
        private global::System.Boolean _Current;
        partial void OnCurrentChanging(global::System.Boolean value);
        partial void OnCurrentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FurtherAction_Employee", "FurtherAction")]
        public EntityCollection<FurtherAction> FurtherActions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FurtherAction>("LightSwitchApplication.FurtherAction_Employee", "FurtherAction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FurtherAction>("LightSwitchApplication.FurtherAction_Employee", "FurtherAction", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "Issue_Employee", "Issue")]
        public EntityCollection<Issue> IssueAssignments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Issue>("LightSwitchApplication.Issue_Employee", "Issue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Issue>("LightSwitchApplication.Issue_Employee", "Issue", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "Issue_Employee1", "Issue")]
        public EntityCollection<Issue> OwnedIssues
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Issue>("LightSwitchApplication.Issue_Employee1", "Issue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Issue>("LightSwitchApplication.Issue_Employee1", "Issue", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="FurtherAction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FurtherAction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FurtherAction object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="issueAction_Issue">Initial value of the IssueAction_Issue property.</param>
        /// <param name="actionTitle">Initial value of the ActionTitle property.</param>
        /// <param name="issueAction_Employee">Initial value of the IssueAction_Employee property.</param>
        /// <param name="percentCompleted">Initial value of the PercentCompleted property.</param>
        /// <param name="priority">Initial value of the Priority property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        public static FurtherAction CreateFurtherAction(global::System.Int32 id, global::System.Int32 issueAction_Issue, global::System.String actionTitle, global::System.Int32 issueAction_Employee, global::System.Decimal percentCompleted, global::System.String priority, global::System.String status, global::System.Byte[] rowVersion)
        {
            FurtherAction furtherAction = new FurtherAction();
            furtherAction.Id = id;
            furtherAction.IssueAction_Issue = issueAction_Issue;
            furtherAction.ActionTitle = actionTitle;
            furtherAction.IssueAction_Employee = issueAction_Employee;
            furtherAction.PercentCompleted = percentCompleted;
            furtherAction.Priority = priority;
            furtherAction.Status = status;
            furtherAction.RowVersion = rowVersion;
            return furtherAction;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IssueAction_Issue
        {
            get
            {
                return _IssueAction_Issue;
            }
            set
            {
                OnIssueAction_IssueChanging(value);
                ReportPropertyChanging("IssueAction_Issue");
                _IssueAction_Issue = value;
                ReportPropertyChanged("IssueAction_Issue");
                OnIssueAction_IssueChanged();
            }
        }
        private global::System.Int32 _IssueAction_Issue;
        partial void OnIssueAction_IssueChanging(global::System.Int32 value);
        partial void OnIssueAction_IssueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ActionTitle
        {
            get
            {
                return _ActionTitle;
            }
            set
            {
                OnActionTitleChanging(value);
                ReportPropertyChanging("ActionTitle");
                _ActionTitle = value;
                ReportPropertyChanged("ActionTitle");
                OnActionTitleChanged();
            }
        }
        private global::System.String _ActionTitle;
        partial void OnActionTitleChanging(global::System.String value);
        partial void OnActionTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IssueAction_Employee
        {
            get
            {
                return _IssueAction_Employee;
            }
            set
            {
                OnIssueAction_EmployeeChanging(value);
                ReportPropertyChanging("IssueAction_Employee");
                _IssueAction_Employee = value;
                ReportPropertyChanged("IssueAction_Employee");
                OnIssueAction_EmployeeChanged();
            }
        }
        private global::System.Int32 _IssueAction_Employee;
        partial void OnIssueAction_EmployeeChanging(global::System.Int32 value);
        partial void OnIssueAction_EmployeeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ActionOutcome
        {
            get
            {
                return _ActionOutcome;
            }
            set
            {
                OnActionOutcomeChanging(value);
                ReportPropertyChanging("ActionOutcome");
                _ActionOutcome = value;
                ReportPropertyChanged("ActionOutcome");
                OnActionOutcomeChanged();
            }
        }
        private global::System.String _ActionOutcome;
        partial void OnActionOutcomeChanging(global::System.String value);
        partial void OnActionOutcomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateAssigned
        {
            get
            {
                return _DateAssigned;
            }
            set
            {
                OnDateAssignedChanging(value);
                ReportPropertyChanging("DateAssigned");
                _DateAssigned = value;
                ReportPropertyChanged("DateAssigned");
                OnDateAssignedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateAssigned;
        partial void OnDateAssignedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateAssignedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TargetCompletionDate
        {
            get
            {
                return _TargetCompletionDate;
            }
            set
            {
                OnTargetCompletionDateChanging(value);
                ReportPropertyChanging("TargetCompletionDate");
                _TargetCompletionDate = value;
                ReportPropertyChanged("TargetCompletionDate");
                OnTargetCompletionDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _TargetCompletionDate;
        partial void OnTargetCompletionDateChanging(Nullable<global::System.DateTime> value);
        partial void OnTargetCompletionDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PercentCompleted
        {
            get
            {
                return _PercentCompleted;
            }
            set
            {
                OnPercentCompletedChanging(value);
                ReportPropertyChanging("PercentCompleted");
                _PercentCompleted = value;
                ReportPropertyChanged("PercentCompleted");
                OnPercentCompletedChanged();
            }
        }
        private global::System.Decimal _PercentCompleted;
        partial void OnPercentCompletedChanging(global::System.Decimal value);
        partial void OnPercentCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = value;
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private global::System.String _Priority;
        partial void OnPriorityChanging(global::System.String value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = value;
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCompleted
        {
            get
            {
                return _DateCompleted;
            }
            set
            {
                OnDateCompletedChanging(value);
                ReportPropertyChanging("DateCompleted");
                _DateCompleted = value;
                ReportPropertyChanged("DateCompleted");
                OnDateCompletedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCompleted;
        partial void OnDateCompletedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FurtherAction_Issue", "Issue")]
        public Issue Issue
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Issue>("LightSwitchApplication.FurtherAction_Issue", "Issue").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Issue>("LightSwitchApplication.FurtherAction_Issue", "Issue").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Issue> IssueReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Issue>("LightSwitchApplication.FurtherAction_Issue", "Issue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Issue>("LightSwitchApplication.FurtherAction_Issue", "Issue", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FurtherAction_Employee", "Employee")]
        public Employee AssignedTo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("LightSwitchApplication.FurtherAction_Employee", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("LightSwitchApplication.FurtherAction_Employee", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> AssignedToReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("LightSwitchApplication.FurtherAction_Employee", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("LightSwitchApplication.FurtherAction_Employee", "Employee", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Issue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Issue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Issue object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="issueTitle">Initial value of the IssueTitle property.</param>
        /// <param name="dateRaised">Initial value of the DateRaised property.</param>
        /// <param name="issueDescription">Initial value of the IssueDescription property.</param>
        /// <param name="issue_Employee1">Initial value of the Issue_Employee1 property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="priority">Initial value of the Priority property.</param>
        /// <param name="issueType_Issue">Initial value of the IssueType_Issue property.</param>
        /// <param name="targetResolutionDate">Initial value of the TargetResolutionDate property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        public static Issue CreateIssue(global::System.Int32 id, global::System.String issueTitle, global::System.DateTime dateRaised, global::System.String issueDescription, global::System.Int32 issue_Employee1, global::System.String status, global::System.String priority, global::System.Int32 issueType_Issue, global::System.DateTime targetResolutionDate, global::System.Byte[] rowVersion)
        {
            Issue issue = new Issue();
            issue.Id = id;
            issue.IssueTitle = issueTitle;
            issue.DateRaised = dateRaised;
            issue.IssueDescription = issueDescription;
            issue.Issue_Employee1 = issue_Employee1;
            issue.Status = status;
            issue.Priority = priority;
            issue.IssueType_Issue = issueType_Issue;
            issue.TargetResolutionDate = targetResolutionDate;
            issue.RowVersion = rowVersion;
            return issue;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IssueTitle
        {
            get
            {
                return _IssueTitle;
            }
            set
            {
                OnIssueTitleChanging(value);
                ReportPropertyChanging("IssueTitle");
                _IssueTitle = value;
                ReportPropertyChanged("IssueTitle");
                OnIssueTitleChanged();
            }
        }
        private global::System.String _IssueTitle;
        partial void OnIssueTitleChanging(global::System.String value);
        partial void OnIssueTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateRaised
        {
            get
            {
                return _DateRaised;
            }
            set
            {
                OnDateRaisedChanging(value);
                ReportPropertyChanging("DateRaised");
                _DateRaised = value;
                ReportPropertyChanged("DateRaised");
                OnDateRaisedChanged();
            }
        }
        private global::System.DateTime _DateRaised;
        partial void OnDateRaisedChanging(global::System.DateTime value);
        partial void OnDateRaisedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IssueDescription
        {
            get
            {
                return _IssueDescription;
            }
            set
            {
                OnIssueDescriptionChanging(value);
                ReportPropertyChanging("IssueDescription");
                _IssueDescription = value;
                ReportPropertyChanged("IssueDescription");
                OnIssueDescriptionChanged();
            }
        }
        private global::System.String _IssueDescription;
        partial void OnIssueDescriptionChanging(global::System.String value);
        partial void OnIssueDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Issue_Employee1
        {
            get
            {
                return _Issue_Employee1;
            }
            set
            {
                OnIssue_Employee1Changing(value);
                ReportPropertyChanging("Issue_Employee1");
                _Issue_Employee1 = value;
                ReportPropertyChanged("Issue_Employee1");
                OnIssue_Employee1Changed();
            }
        }
        private global::System.Int32 _Issue_Employee1;
        partial void OnIssue_Employee1Changing(global::System.Int32 value);
        partial void OnIssue_Employee1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = value;
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = value;
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private global::System.String _Priority;
        partial void OnPriorityChanging(global::System.String value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IssueType_Issue
        {
            get
            {
                return _IssueType_Issue;
            }
            set
            {
                OnIssueType_IssueChanging(value);
                ReportPropertyChanging("IssueType_Issue");
                _IssueType_Issue = value;
                ReportPropertyChanged("IssueType_Issue");
                OnIssueType_IssueChanged();
            }
        }
        private global::System.Int32 _IssueType_Issue;
        partial void OnIssueType_IssueChanging(global::System.Int32 value);
        partial void OnIssueType_IssueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Issue_Employee
        {
            get
            {
                return _Issue_Employee;
            }
            set
            {
                OnIssue_EmployeeChanging(value);
                ReportPropertyChanging("Issue_Employee");
                _Issue_Employee = value;
                ReportPropertyChanged("Issue_Employee");
                OnIssue_EmployeeChanged();
            }
        }
        private Nullable<global::System.Int32> _Issue_Employee;
        partial void OnIssue_EmployeeChanging(Nullable<global::System.Int32> value);
        partial void OnIssue_EmployeeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IssueImpactAssessment
        {
            get
            {
                return _IssueImpactAssessment;
            }
            set
            {
                OnIssueImpactAssessmentChanging(value);
                ReportPropertyChanging("IssueImpactAssessment");
                _IssueImpactAssessment = value;
                ReportPropertyChanged("IssueImpactAssessment");
                OnIssueImpactAssessmentChanged();
            }
        }
        private global::System.String _IssueImpactAssessment;
        partial void OnIssueImpactAssessmentChanging(global::System.String value);
        partial void OnIssueImpactAssessmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TargetResolutionDate
        {
            get
            {
                return _TargetResolutionDate;
            }
            set
            {
                OnTargetResolutionDateChanging(value);
                ReportPropertyChanging("TargetResolutionDate");
                _TargetResolutionDate = value;
                ReportPropertyChanged("TargetResolutionDate");
                OnTargetResolutionDateChanged();
            }
        }
        private global::System.DateTime _TargetResolutionDate;
        partial void OnTargetResolutionDateChanging(global::System.DateTime value);
        partial void OnTargetResolutionDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CorrectiveAction
        {
            get
            {
                return _CorrectiveAction;
            }
            set
            {
                OnCorrectiveActionChanging(value);
                ReportPropertyChanging("CorrectiveAction");
                _CorrectiveAction = value;
                ReportPropertyChanged("CorrectiveAction");
                OnCorrectiveActionChanged();
            }
        }
        private global::System.String _CorrectiveAction;
        partial void OnCorrectiveActionChanging(global::System.String value);
        partial void OnCorrectiveActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CorrectiveActionCompletionTargetDate
        {
            get
            {
                return _CorrectiveActionCompletionTargetDate;
            }
            set
            {
                OnCorrectiveActionCompletionTargetDateChanging(value);
                ReportPropertyChanging("CorrectiveActionCompletionTargetDate");
                _CorrectiveActionCompletionTargetDate = value;
                ReportPropertyChanged("CorrectiveActionCompletionTargetDate");
                OnCorrectiveActionCompletionTargetDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CorrectiveActionCompletionTargetDate;
        partial void OnCorrectiveActionCompletionTargetDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCorrectiveActionCompletionTargetDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCorrectiveActionCompleted
        {
            get
            {
                return _DateCorrectiveActionCompleted;
            }
            set
            {
                OnDateCorrectiveActionCompletedChanging(value);
                ReportPropertyChanging("DateCorrectiveActionCompleted");
                _DateCorrectiveActionCompleted = value;
                ReportPropertyChanged("DateCorrectiveActionCompleted");
                OnDateCorrectiveActionCompletedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCorrectiveActionCompleted;
        partial void OnDateCorrectiveActionCompletedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCorrectiveActionCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PreventativeAction
        {
            get
            {
                return _PreventativeAction;
            }
            set
            {
                OnPreventativeActionChanging(value);
                ReportPropertyChanging("PreventativeAction");
                _PreventativeAction = value;
                ReportPropertyChanged("PreventativeAction");
                OnPreventativeActionChanged();
            }
        }
        private global::System.String _PreventativeAction;
        partial void OnPreventativeActionChanging(global::System.String value);
        partial void OnPreventativeActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PreventativeActionCompletionTargetDate
        {
            get
            {
                return _PreventativeActionCompletionTargetDate;
            }
            set
            {
                OnPreventativeActionCompletionTargetDateChanging(value);
                ReportPropertyChanging("PreventativeActionCompletionTargetDate");
                _PreventativeActionCompletionTargetDate = value;
                ReportPropertyChanged("PreventativeActionCompletionTargetDate");
                OnPreventativeActionCompletionTargetDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PreventativeActionCompletionTargetDate;
        partial void OnPreventativeActionCompletionTargetDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPreventativeActionCompletionTargetDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DatePreventativeActionCompleted
        {
            get
            {
                return _DatePreventativeActionCompleted;
            }
            set
            {
                OnDatePreventativeActionCompletedChanging(value);
                ReportPropertyChanging("DatePreventativeActionCompleted");
                _DatePreventativeActionCompleted = value;
                ReportPropertyChanged("DatePreventativeActionCompleted");
                OnDatePreventativeActionCompletedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DatePreventativeActionCompleted;
        partial void OnDatePreventativeActionCompletedChanging(Nullable<global::System.DateTime> value);
        partial void OnDatePreventativeActionCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateIssueClosed
        {
            get
            {
                return _DateIssueClosed;
            }
            set
            {
                OnDateIssueClosedChanging(value);
                ReportPropertyChanging("DateIssueClosed");
                _DateIssueClosed = value;
                ReportPropertyChanged("DateIssueClosed");
                OnDateIssueClosedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateIssueClosed;
        partial void OnDateIssueClosedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateIssueClosedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "Issue_Employee1", "Employee")]
        public Employee IssueOwner
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("LightSwitchApplication.Issue_Employee1", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("LightSwitchApplication.Issue_Employee1", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> IssueOwnerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("LightSwitchApplication.Issue_Employee1", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("LightSwitchApplication.Issue_Employee1", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "IssueType_Issue", "IssueType")]
        public IssueType IssueType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IssueType>("LightSwitchApplication.IssueType_Issue", "IssueType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IssueType>("LightSwitchApplication.IssueType_Issue", "IssueType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<IssueType> IssueTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<IssueType>("LightSwitchApplication.IssueType_Issue", "IssueType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<IssueType>("LightSwitchApplication.IssueType_Issue", "IssueType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "Issue_Employee", "Employee")]
        public Employee AssignedTo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("LightSwitchApplication.Issue_Employee", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("LightSwitchApplication.Issue_Employee", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> AssignedToReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("LightSwitchApplication.Issue_Employee", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("LightSwitchApplication.Issue_Employee", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "FurtherAction_Issue", "FurtherAction")]
        public EntityCollection<FurtherAction> FurtherActions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FurtherAction>("LightSwitchApplication.FurtherAction_Issue", "FurtherAction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FurtherAction>("LightSwitchApplication.FurtherAction_Issue", "FurtherAction", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "IssueComment_Issue", "IssueComment")]
        public EntityCollection<IssueComment> IssueComments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<IssueComment>("LightSwitchApplication.IssueComment_Issue", "IssueComment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<IssueComment>("LightSwitchApplication.IssueComment_Issue", "IssueComment", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="IssueComment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IssueComment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IssueComment object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="comment">Initial value of the Comment property.</param>
        /// <param name="commentDate">Initial value of the CommentDate property.</param>
        /// <param name="issueComment_Issue">Initial value of the IssueComment_Issue property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        public static IssueComment CreateIssueComment(global::System.Int32 id, global::System.String comment, global::System.DateTime commentDate, global::System.Int32 issueComment_Issue, global::System.Byte[] rowVersion)
        {
            IssueComment issueComment = new IssueComment();
            issueComment.Id = id;
            issueComment.Comment = comment;
            issueComment.CommentDate = commentDate;
            issueComment.IssueComment_Issue = issueComment_Issue;
            issueComment.RowVersion = rowVersion;
            return issueComment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = value;
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CommentDate
        {
            get
            {
                return _CommentDate;
            }
            set
            {
                OnCommentDateChanging(value);
                ReportPropertyChanging("CommentDate");
                _CommentDate = value;
                ReportPropertyChanged("CommentDate");
                OnCommentDateChanged();
            }
        }
        private global::System.DateTime _CommentDate;
        partial void OnCommentDateChanging(global::System.DateTime value);
        partial void OnCommentDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IssueComment_Issue
        {
            get
            {
                return _IssueComment_Issue;
            }
            set
            {
                OnIssueComment_IssueChanging(value);
                ReportPropertyChanging("IssueComment_Issue");
                _IssueComment_Issue = value;
                ReportPropertyChanged("IssueComment_Issue");
                OnIssueComment_IssueChanged();
            }
        }
        private global::System.Int32 _IssueComment_Issue;
        partial void OnIssueComment_IssueChanging(global::System.Int32 value);
        partial void OnIssueComment_IssueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "IssueComment_Issue", "Issue")]
        public Issue Issue
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Issue>("LightSwitchApplication.IssueComment_Issue", "Issue").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Issue>("LightSwitchApplication.IssueComment_Issue", "Issue").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Issue> IssueReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Issue>("LightSwitchApplication.IssueComment_Issue", "Issue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Issue>("LightSwitchApplication.IssueComment_Issue", "Issue", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="IssueType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class IssueType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new IssueType object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="issueTypeName">Initial value of the IssueTypeName property.</param>
        /// <param name="rowVersion">Initial value of the RowVersion property.</param>
        public static IssueType CreateIssueType(global::System.Int32 id, global::System.String issueTypeName, global::System.Byte[] rowVersion)
        {
            IssueType issueType = new IssueType();
            issueType.Id = id;
            issueType.IssueTypeName = issueTypeName;
            issueType.RowVersion = rowVersion;
            return issueType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IssueTypeName
        {
            get
            {
                return _IssueTypeName;
            }
            set
            {
                OnIssueTypeNameChanging(value);
                ReportPropertyChanging("IssueTypeName");
                _IssueTypeName = value;
                ReportPropertyChanged("IssueTypeName");
                OnIssueTypeNameChanged();
            }
        }
        private global::System.String _IssueTypeName;
        partial void OnIssueTypeNameChanging(global::System.String value);
        partial void OnIssueTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LightSwitchApplication", "IssueType_Issue", "Issue")]
        public EntityCollection<Issue> Issues
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Issue>("LightSwitchApplication.IssueType_Issue", "Issue");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Issue>("LightSwitchApplication.IssueType_Issue", "Issue", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
