//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.ApplicationData>
    {
    
        public ApplicationDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).ApplicationData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ApplicationDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.ApplicationData>
    {
        public ApplicationDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.FurtherAction> MyFurtherActions()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.FurtherAction> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.FurtherAction>("FurtherActions");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Issue> InProgressIssues()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Issue> query;
            global::System.DateTime today1 = global::Microsoft.LightSwitch.RelativeDates.Today();
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::LightSwitchApplication.Implementation.Issue>("Issues"),
                (i) => ((i.Status.CompareTo("ASG") == 0) && (i.TargetResolutionDate >= today1)));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Issue> IssuesDueToday()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Issue> query;
            global::System.DateTime today1 = global::Microsoft.LightSwitch.RelativeDates.Today();
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::LightSwitchApplication.Implementation.Issue>("Issues"),
                (i) => (i.TargetResolutionDate == today1));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Issue> MyIssues()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Issue> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.Issue>("Issues");
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Issue> OverDueIssues()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Issue> query;
            global::System.DateTime today1 = global::Microsoft.LightSwitch.RelativeDates.Today();
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::LightSwitchApplication.Implementation.Issue>("Issues"),
                (i) => (i.TargetResolutionDate < today1));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Issue> UnassignedIssues()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Issue> query;
            global::System.DateTime today1 = global::Microsoft.LightSwitch.RelativeDates.Today();
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::LightSwitchApplication.Implementation.Issue>("Issues"),
                (i) => ((i.Status.CompareTo("UAG") == 0) && (i.TargetResolutionDate >= today1)));
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.FurtherAction))
            {
                return new global::LightSwitchApplication.Implementation.FurtherAction();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.IssueComment))
            {
                return new global::LightSwitchApplication.Implementation.IssueComment();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Issue))
            {
                return new global::LightSwitchApplication.Implementation.Issue();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.IssueType))
            {
                return new global::LightSwitchApplication.Implementation.IssueType();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.ApplicationData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.ApplicationData(this.GetEntityConnectionString(
                "_IntrinsicData",
                "res://" + assemblyName + "/ApplicationData.csdl|res://" + assemblyName + "/ApplicationData.ssdl|res://" + assemblyName + "/ApplicationData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Employee))
            {
                return new global::LightSwitchApplication.Implementation.Employee();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.FurtherAction))
            {
                return new global::LightSwitchApplication.Implementation.FurtherAction();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.IssueComment))
            {
                return new global::LightSwitchApplication.Implementation.IssueComment();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Issue))
            {
                return new global::LightSwitchApplication.Implementation.Issue();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.IssueType))
            {
                return new global::LightSwitchApplication.Implementation.IssueType();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.ApplicationDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationDataService))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Employee) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Employee);
            }
            if (typeof(global::LightSwitchApplication.FurtherAction) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.FurtherAction);
            }
            if (typeof(global::LightSwitchApplication.IssueComment) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.IssueComment);
            }
            if (typeof(global::LightSwitchApplication.Issue) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Issue);
            }
            if (typeof(global::LightSwitchApplication.IssueType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.IssueType);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Employee :
        global::LightSwitchApplication.Employee.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.FurtherActions
        {
            get
            {
                return this.FurtherActions;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.IssueAssignments
        {
            get
            {
                return this.IssueAssignments;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Employee.DetailsClass.IImplementation.OwnedIssues
        {
            get
            {
                return this.OwnedIssues;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class FurtherAction :
        global::LightSwitchApplication.FurtherAction.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.FurtherAction.DetailsClass.IImplementation.Issue
        {
            get
            {
                return this.Issue;
            }
            set
            {
                this.Issue = (global::LightSwitchApplication.Implementation.Issue)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Issue");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.FurtherAction.DetailsClass.IImplementation.AssignedTo
        {
            get
            {
                return this.AssignedTo;
            }
            set
            {
                this.AssignedTo = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("AssignedTo");
                }
            }
        }
        
        partial void OnIssueAction_IssueChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Issue");
            }
        }
        
        partial void OnIssueAction_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("AssignedTo");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class IssueComment :
        global::LightSwitchApplication.IssueComment.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.IssueComment.DetailsClass.IImplementation.Issue
        {
            get
            {
                return this.Issue;
            }
            set
            {
                this.Issue = (global::LightSwitchApplication.Implementation.Issue)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Issue");
                }
            }
        }
        
        partial void OnIssueComment_IssueChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Issue");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Issue :
        global::LightSwitchApplication.Issue.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Issue.DetailsClass.IImplementation.IssueOwner
        {
            get
            {
                return this.IssueOwner;
            }
            set
            {
                this.IssueOwner = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("IssueOwner");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Issue.DetailsClass.IImplementation.IssueType
        {
            get
            {
                return this.IssueType;
            }
            set
            {
                this.IssueType = (global::LightSwitchApplication.Implementation.IssueType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("IssueType");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Issue.DetailsClass.IImplementation.AssignedTo
        {
            get
            {
                return this.AssignedTo;
            }
            set
            {
                this.AssignedTo = (global::LightSwitchApplication.Implementation.Employee)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("AssignedTo");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Issue.DetailsClass.IImplementation.FurtherActions
        {
            get
            {
                return this.FurtherActions;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Issue.DetailsClass.IImplementation.IssueComments
        {
            get
            {
                return this.IssueComments;
            }
        }
        
        partial void OnIssue_Employee1Changed()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("IssueOwner");
            }
        }
        
        partial void OnIssueType_IssueChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("IssueType");
            }
        }
        
        partial void OnIssue_EmployeeChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("AssignedTo");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class IssueType :
        global::LightSwitchApplication.IssueType.DetailsClass.IImplementation,
        global::Microsoft.LightSwitch.Internal.ICreatedModifiedPropertiesImplementation
    
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.IssueType.DetailsClass.IImplementation.Issues
        {
            get
            {
                return this.Issues;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

